name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress commnad line
        default: npx cypress run

jobs:  
  cypress-chrome-tests: 
    runs-on: ubuntu-latest
    container:
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v3.5.2
        
      - name: Run E2E tests
        with: 
          install-command: npm install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.cli }}
        
